const Quote = require('../models/Quote');
const Invoice = require('../models/Invoice');
const Review = require('../models/Review');
const Dispute = require('../models/Dispute');

const item = ({ timestamp, type, actor = null, description, resourceType, resourceId, evidence = [] }) => ({
  timestamp,
  type,
  actor,
  description,
  relatedResource: { resourceType, resourceId },
  evidence,
});

const buildServiceTrace = async ({ serviceRequest, booking }) => {
  const [quote, invoice, review, disputes] = await Promise.all([
    Quote.findById(booking.acceptedQuote).lean(),
    Invoice.findOne({ booking: booking._id }).lean(),
    Review.findOne({ booking: booking._id }).lean(),
    Dispute.find({ booking: booking._id }).sort({ createdAt: 1 }).lean(),
  ]);

  const timeline = [
    item({
      timestamp: serviceRequest.createdAt,
      type: 'SERVICE_REQUEST_CREATED',
      actor: serviceRequest.customer,
      description: serviceRequest.title,
      resourceType: 'ServiceRequest',
      resourceId: serviceRequest._id,
    }),
  ];

  if (serviceRequest.aiUnderstanding?.generatedAt) {
    timeline.push(item({
      timestamp: serviceRequest.aiUnderstanding.generatedAt,
      type: 'REQUEST_UNDERSTOOD',
      description: `Request understanding generated by ${serviceRequest.aiUnderstanding.source}.`,
      resourceType: 'ServiceRequest',
      resourceId: serviceRequest._id,
    }));
  }

  if (quote) {
    timeline.push(item({
      timestamp: quote.acceptedAt || quote.updatedAt,
      type: 'QUOTE_ACCEPTED',
      actor: serviceRequest.customer,
      description: quote.scope.summary,
      resourceType: 'Quote',
      resourceId: quote._id,
    }));
  }

  booking.statusEvents.forEach((event) => {
    timeline.push(item({
      timestamp: event.timestamp,
      type: event.type,
      actor: event.actor,
      description: event.description,
      resourceType: 'Booking',
      resourceId: booking._id,
    }));
  });

  booking.evidence.forEach((evidence) => {
    timeline.push(item({
      timestamp: evidence.createdAt,
      type: 'EVIDENCE_ADDED',
      actor: evidence.uploadedBy,
      description: evidence.description || evidence.type,
      resourceType: 'Booking',
      resourceId: booking._id,
      evidence: [evidence],
    }));
  });

  booking.scopeChanges.forEach((change) => {
    timeline.push(item({
      timestamp: change.createdAt,
      type: `SCOPE_CHANGE_${change.status}`,
      actor: change.requestedBy,
      description: change.reason,
      resourceType: 'Booking',
      resourceId: booking._id,
    }));
  });

  if (invoice) {
    timeline.push(item({
      timestamp: invoice.issuedAt || invoice.createdAt,
      type: 'INVOICE_ISSUED',
      description: `Invoice ${invoice.invoiceNumber} issued.`,
      resourceType: 'Invoice',
      resourceId: invoice._id,
    }));
  }

  if (review) {
    timeline.push(item({
      timestamp: review.createdAt,
      type: 'REVIEW_SUBMITTED',
      actor: review.customer,
      description: `${review.rating} star review submitted.`,
      resourceType: 'Review',
      resourceId: review._id,
    }));
  }

  disputes.forEach((dispute) => {
    timeline.push(item({
      timestamp: dispute.createdAt,
      type: 'DISPUTE_OPENED',
      actor: dispute.openedBy,
      description: dispute.reason,
      resourceType: 'Dispute',
      resourceId: dispute._id,
    }));
  });

  timeline.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));

  return {
    serviceRequest,
    quote,
    booking,
    invoice,
    review,
    disputes,
    timeline,
  };
};

module.exports = {
  buildServiceTrace,
};
